service: auction-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  memorySize: 256
  timeout: 10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  profile: ${opt:profile, 'vekaevdev'}
  tracing:
    lambda: true
    apiGateway: true
  apiGateway:
    minimumCompressionSize: 1024
  iam:
    role:
      statements:
        - ${file(serverless/iam/SecretsIAM.yml):SecretsIAM}
        - ${file(serverless/iam/AuctionsTableIAM.yml):AuctionsTableIAM}
  environment:
    AWS_DB_REGION: ${self:provider.region}
    AWS_DB_PROFILE: ${self:provider.profile}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
    AUTH0_PUBLIC_KEY: ${ssm:${self:custom.ssmBasePath}/AUTH0_PUBLIC_KEY}

package:
  individually: true
  patterns:
    - '!test/**'
    - '!.git/**'
    - '!.idea/**'
    - '!.jest/**'
    - '!.husky/**'
    - '!.github/**'
    - '!.serverless/**'
    - '!node_modules/.cache/**'
    - '!.nvmrc'
    - '!.npmrc'
    - '!.coverage'
    - '!.eslintrc'
    - '!.gitignore'
    - '!.prettierrc'
    - '!.gitattributes'
    - '!yarn.lock'
    - '!README.md'

functions:
  authorizer:
    handler: src/functions/authorizer.handler
  getAuctions:
    handler: src/functions/auctions/getAuctions.handler
    events:
      - http:
          method: GET
          path: /auctions
  getAuction:
    handler: src/functions/auctions/getAuction.handler
    events:
      - http:
          method: GET
          path: /auctions/{id}
          authorizer: authorizer
  createAuction:
    handler: src/functions/auctions/createAuction.handler
    events:
      - http:
          method: POST
          path: /auctions
          authorizer: authorizer
  updateAuction:
    handler: src/functions/auctions/updateAuction.handler
    events:
      - http:
          method: PATCH
          path: /auctions/{id}
          authorizer: authorizer
  deleteAuction:
    handler: src/functions/auctions/deleteAuction.handler
    events:
      - http:
          method: DELETE
          path: /auctions/{id}
          authorizer: authorizer
  placeBid:
    handler: src/functions/auctions/placeBid.handler
    events:
      - http:
          method: POST
          path: /auctions/{id}/bid
          authorizer: authorizer
  processAuctions:
    handler: src/functions/auctions/processAuctions.handler
    events:
      - http:
          method: POST
          path: /auctions/process
          authorizer: authorizer

resources:
  Resources:
    AuctionsTable: ${file(serverless/resources/AuctionsTable.yml):AuctionsTable}
    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: ApiGatewayRestApi

plugins:
#   - serverless-auto-swagger
  - serverless-analyze-bundle-plugin
  - serverless-esbuild
  - serverless-offline
  - serverless-cloudside-plugin
  - serverless-prune-plugin

custom:
  ssmBasePath: /aws/reference/secretsmanager/${self:service}/${self:provider.stage}
  AuctionsTable:
    name: !Ref AuctionsTable
    arn:  !GetAtt AuctionsTable.Arn
  # PLUGINS CONFIGS
  serverless-offline:
    httpPort: 3001
    noPrependStageInUrl: true
  esbuild:
    packager: yarn
    minify: true
    keepNames: true
    exclude: ['aws-sdk', '@aws-sdk/client-dynamodb', '@aws-sdk/util-dynamodb', '@aws-sdk/credential-providers']
    installExtraArgs: ['--max-old-space-size=4096']
    watch:
      pattern: ['src/**/*.ts']
  prune:
    automatic: true
    number: 1
  autoswagger:
    typefiles: []
