service: auction-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  memorySize: 256
  timeout: 10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  profile: ${opt:profile, 'vekaevdev'}
  tracing:
    lambda: true
    apiGateway: true
  apiGateway:
    minimumCompressionSize: 1024
  iam:
    role:
      statements:
        - ${file(serverless/iam/SecretsIAM.yml):SecretsIAM}
        - ${file(serverless/iam/SendMailIAM.yml):SendMailIAM}
        - ${file(serverless/iam/MailQueueIAM.yml):MailQueueIAM}
        - ${file(serverless/iam/AuctionsTableIAM.yml):AuctionsTableIAM}
        - ${file(serverless/iam/AuctionsBucketIAM.yml):AuctionsBucketIAM}
  environment:
    ENV: ${self:provider.stage}
    AWS_DB_REGION: ${self:provider.region}
    AWS_DB_PROFILE: ${self:provider.profile}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    MAIL_QUEUE_URL: ${self:custom.MailQueue.url}
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
    AUCTIONS_BUCKET_NAME: ${self:custom.AuctionsBucket.name}
    AUTH0_PUBLIC_KEY: ${ssm:${self:custom.ssmBasePath}/AUTH0_PUBLIC_KEY}

package:
  individually: true
  patterns:
    - '!test/**'
    - '!.git/**'
    - '!.idea/**'
    - '!.jest/**'
    - '!.husky/**'
    - '!.github/**'
    - '!.serverless/**'
    - '!node_modules/.cache/**'
    - '!.nvmrc'
    - '!.npmrc'
    - '!.coverage'
    - '!.eslintrc'
    - '!.gitignore'
    - '!.prettierrc'
    - '!.gitattributes'
    - '!yarn.lock'
    - '!README.md'

functions:
  authorizer:
    handler: src/functions/authorizer.handler
  getAuctions:
    handler: src/functions/auctions/getAuctions.handler
    events:
      - http:
          method: GET
          path: /auctions
          cors: true
  getAuction:
    handler: src/functions/auctions/getAuction.handler
    events:
      - http:
          method: GET
          path: /auctions/{id}
          authorizer: authorizer
          cors: true
  createAuction:
    handler: src/functions/auctions/createAuction.handler
    events:
      - http:
          method: POST
          path: /auctions
          authorizer: authorizer
          cors: true
  updateAuction:
    handler: src/functions/auctions/updateAuction.handler
    events:
      - http:
          method: PATCH
          path: /auctions/{id}
          authorizer: authorizer
          cors: true
  deleteAuction:
    handler: src/functions/auctions/deleteAuction.handler
    events:
      - http:
          method: DELETE
          path: /auctions/{id}
          authorizer: authorizer
          cors: true
  placeBid:
    handler: src/functions/auctions/placeBid.handler
    events:
      - http:
          method: POST
          path: /auctions/{id}/bid
          authorizer: authorizer
          cors: true
  processAuctions:
    handler: src/functions/auctions/processAuctions.handler
    events:
      - http:
          method: POST
          path: /auctions/process
          authorizer: authorizer
          cors: true
      - schedule: rate(30 minutes)
  sendMail:
    handler: src/functions/notification/sendMail.handler
    events:
      - sqs:
          arn: ${self:custom.MailQueue.arn}
          batchSize: 1

resources:
  Resources:
    MailQueue: ${file(serverless/resources/MailQueue.yml):MailQueue}
    AuctionsTable: ${file(serverless/resources/AuctionsTable.yml):AuctionsTable}
    AuctionsBucket: ${file(serverless/resources/AuctionsBucket.yml):AuctionsBucket}
    AuctionsBucketPolicy: ${file(serverless/resources/AuctionsBucket.yml):AuctionsBucketPolicy}
    GatewayResponseDefault4XX: ${file(serverless/resources/GatewayResponse.yml):GatewayResponseDefault4XX}

plugins:
#   - serverless-auto-swagger
  - serverless-analyze-bundle-plugin
  - serverless-esbuild
  - serverless-offline
  - serverless-cloudside-plugin
  - serverless-prune-plugin

custom:
  ssmBasePath: /aws/reference/secretsmanager/${self:service}/${self:provider.stage}
  MailQueue:
    url: !Ref MailQueue
    arn: !GetAtt MailQueue.Arn
    name: MailQueue-${self:service}-${self:provider.stage}
  AuctionsTable:
    name: !Ref AuctionsTable
    arn:  !GetAtt AuctionsTable.Arn
  AuctionsBucket:
    name: auctions-bucket-${self:service}-${self:provider.stage}
  serverless-offline:
    httpPort: 3001
    noPrependStageInUrl: true
  esbuild:
    packager: yarn
    minify: true
    keepNames: true
    exclude:
      - 'aws-sdk'
      - '@aws-sdk/*'
    installExtraArgs: ['--max-old-space-size=4096']
    watch:
      pattern: ['src/**/*.ts']
  prune:
    automatic: true
    number: 1
  autoswagger:
    typefiles: []
