service: auction-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 128
  timeout: 10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  profile: ${opt:profile, 'vekaevdev'}
  apiGateway:
    minimumCompressionSize: 1024
  iam:
    role:
      statements:
        - ${file(serverless/iam/AuctionsTableIAM.yml):AuctionsTableIAM}
  environment:
    AWS_DB_REGION: ${self:provider.region}
    AWS_DB_PROFILE: ${self:provider.profile}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'

package:
  individually: false

functions:
  getAuctions:
    handler: src/functions.getAuctions
    events:
      - http:
          method: GET
          path: /auctions
  getAuction:
    handler: src/functions.getAuction
    events:
      - http:
          method: GET
          path: /auctions/{id}
  createAuction:
    handler: src/functions.createAuction
    events:
      - http:
          method: POST
          path: /auctions
  updateAuction:
    handler: src/functions.updateAuction
    events:
      - http:
          method: PATCH
          path: /auctions/{id}
  deleteAuction:
    handler: src/functions.deleteAuction
    events:
      - http:
          method: DELETE
          path: /auctions/{id}

resources:
  Resources:
    AuctionsTable: ${file(serverless/resources/AuctionsTable.yml):AuctionsTable}

custom:
  serverless-offline:
    cache: true
    useChildProcesses: true
  AuctionsTable:
    name: !Ref AuctionsTable
    arn:  !GetAtt AuctionsTable.Arn
  esbuild:
    packager: yarn
    minify: true
    keepNames: true
    exclude: ['aws-sdk', '@aws-sdk/client-dynamodb', '@aws-sdk/util-dynamodb', '@aws-sdk/credential-providers']
    watch:
      pattern: ['src/**/*.ts']
  prune:
    automatic: true
    number: 1

plugins:
#   - serverless-auto-swagger
#  NOTE: use serverless-analyze-bundle-plugin with package.individually = true
#  and run with function name at the end
#   - serverless-analyze-bundle-plugin
  - serverless-esbuild
  - serverless-offline
  - serverless-cloudside-plugin
  - serverless-prune-plugin
