name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'
      - name: Install serverless
        run: yarn global add serverless
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Serverless AWS authentication
        run: serverless config credentials --profile default --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy
        run: serverless deploy