name: reviewdog
on: [pull_request]
jobs:
  lint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Run eslint using reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: '--quiet src/'
          fail_on_error: true